using static System.Console;
static int f(int x) => (int)Math.Pow(x, 2) - x + 41;
static bool IsPrime(int n, int f) {
    // Trial division algorithim
    if (n <= 1) return false;
    if (n == 2 || f * f > n) return true;
    if (n % f == 0) return false;
    return IsPrime(n, f + 1);
}
static int FindSmallestFactor(int n) {
    for (int i = 2; i <= Math.Sqrt(n); i++)
        if (n % i == 0) return i;
    return n;
}
WriteLine("The numbers generated by the formula x^2 - x + 41 are:");
for (int x = 1; ; x++) {
    int num = f(x);
    if (IsPrime(num, 2))
        WriteLine(num + "\tprime");
    else {
        int factor = FindSmallestFactor(num);
        WriteLine(num + "\ttest fails/factor = " + factor);
        ReadLine();
        return; // break
    }
    x++;
}
ReadKey();